#!/bin/sh

export PATH=/apache-maven-3.3.3/bin/:$PATH
export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
for i in odlparent affinity bgpcep controller lispflowmapping openflowjava openflowplugin ovsdb/commons/parent vtn yangtools
do (cd "$i" && mvn clean install ); done

